#define ADAPTIVE_PRIO
#define TTC_THRESH 5.0
#define TTC_THRESH_UPPER 15.0
#define CRASH_THRESHOLD 4.6
#define PRIO_MANUEVER_THRESHOLD 5.0
#define MEAN_NODE_SPEED 25
#define STD_DEV 1
#define MIN_INTERVAL 50
#define MAX_INTERVAL 500
